export const trainList = [
  {
    trainNr: 401,
    from: "Stockholm",
    to: "Gothenburg",
    startTime: "09:00",
    endTime: "13:00",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Stockholm",
  },
  {
    trainNr: 501,
    from: "Malmö",
    to: "Lund",
    startTime: "10:15",
    endTime: "10:45",
    delay: 5,
    status: "Delayed",
    reason: "Technical Issue",
    reasonCode: "T01",
    activeLocation: "Malmö",
  },
  {
    trainNr: 110,
    from: "Uppsala",
    to: "Stockholm",
    startTime: "11:00",
    endTime: "11:45",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Uppsala",
  },
  {
    trainNr: 235,
    from: "Helsingborg",
    to: "Gothenburg",
    startTime: "08:00",
    endTime: "10:00",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Helsingborg",
  },
  {
    trainNr: 765,
    from: "Luleå",
    to: "Kiruna",
    startTime: "12:30",
    endTime: "16:00",
    delay: 10,
    status: "Delayed",
    reason: "Weather Condition",
    reasonCode: "W02",
    activeLocation: "Luleå",
  },
  {
    trainNr: 310,
    from: "Norrköping",
    to: "Linköping",
    startTime: "09:10",
    endTime: "09:40",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Norrköping",
  },
  {
    trainNr: 570,
    from: "Örebro",
    to: "Västerås",
    startTime: "14:00",
    endTime: "15:00",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Örebro",
  },
  {
    trainNr: 421,
    from: "Karlstad",
    to: "Stockholm",
    startTime: "15:30",
    endTime: "17:45",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Karlstad",
  },
  {
    trainNr: 690,
    from: "Jönköping",
    to: "Värnamo",
    startTime: "11:50",
    endTime: "12:45",
    delay: 2,
    status: "Delayed",
    reason: "Traffic",
    reasonCode: "T03",
    activeLocation: "Jönköping",
  },
  {
    trainNr: 810,
    from: "Falun",
    to: "Gävle",
    startTime: "16:20",
    endTime: "18:00",
    delay: 0,
    status: "On Time",
    reason: "",
    reasonCode: "",
    activeLocation: "Falun",
  },
];
