name: Cypress test
on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: frontend
          start: npm run dev
